CREATE TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" 
   (	"ALERT_ID" NUMBER, 
	"ALERT_TIMESTAMP" TIMESTAMP (6), 
	"DEVICE_ID" NUMBER, 
	"MESSAGE" CLOB COLLATE "USING_NLS_COMP", 
	"ALERT_STATE" VARCHAR2(32 BYTE) COLLATE "USING_NLS_COMP"
   )  DEFAULT COLLATION "USING_NLS_COMP" ;

CREATE UNIQUE INDEX "LEAWOOD_DEV"."LW_ALERT_LOG_PK" ON "LEAWOOD_DEV"."LW_ALERT_LOG" ("ALERT_ID") 
  ;

CREATE UNIQUE INDEX "LEAWOOD_DEV"."LW_ALERT_LOG_UK1" ON "LEAWOOD_DEV"."LW_ALERT_LOG" ("DEVICE_ID", "ALERT_TIMESTAMP") 
  ;

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" MODIFY ("ALERT_ID" NOT NULL ENABLE);

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" MODIFY ("ALERT_TIMESTAMP" NOT NULL ENABLE);

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" MODIFY ("DEVICE_ID" NOT NULL ENABLE);

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" ADD CONSTRAINT "LW_ALERT_LOG_PK" PRIMARY KEY ("ALERT_ID")
  USING INDEX  ENABLE;

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" ADD CONSTRAINT "LW_ALERT_LOG_UK1" UNIQUE ("DEVICE_ID", "ALERT_TIMESTAMP")
  USING INDEX  ENABLE;

ALTER TABLE "LEAWOOD_DEV"."LW_ALERT_LOG" ADD CONSTRAINT "LW_ALERT_LOG_FK" FOREIGN KEY ("DEVICE_ID")
	  REFERENCES "LEAWOOD_DEV"."LW_DEVICE" ("DEVICE_ID") ON DELETE CASCADE ENABLE;

CREATE OR REPLACE EDITIONABLE TRIGGER "LEAWOOD_DEV"."LW_ALERT_LOG_ID_T1" 
BEFORE
insert or update on "LW_ALERT_LOG"
for each row
begin
    if :new.ALERT_ID is null then
        :new.ALERT_ID := to_number(sys_guid(), 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
        :new.ALERT_TIMESTAMP := systimestamp;
    end if;

end;

/
ALTER TRIGGER "LEAWOOD_DEV"."LW_ALERT_LOG_ID_T1" ENABLE;

